### ISSUE TITLE
Support nested function in function / method as separate break out categories in complexity data.

### ISSUE THREAD

**Issue by yulongheli** [typhonjs-node-escomplex/escomplex-plugin-syntax-estree#1]
Code like this
：

`import React from 'react';

const MainRedirect = React.createClass({
  getInitialState() {
  	const func = ()=> {
      console.log('getInitialState...');
  	}
  },
  render() {
    return null;
  },
});

export default MainRedirect;`

result:
`{
  "methodAggregate": {
    "cyclomatic": 1,
    "cyclomaticDensity": 25,
    "halstead": {
      "bugs": 0.037,
      "difficulty": 6.722,
      "effort": 755.377,
      "length": 26,
      "time": 41.965,
      "vocabulary": 20,
      "volume": 112.37,
      "operands": {
        "distinct": 9,
        "total": 11,
        "identifiers": [
          "React",
          "\"react\"",
          "MainRedirect",
          "createClass",
          "func",
          "console",
          "log",
          "\"getInitialState...\"",
          "null"
        ]
      },
      "operators": {
        "distinct": 11,
        "total": 15,
        "identifiers": [
          "import",
          "from",
          "const",
          "=",
          "()",
          ".",
          "{}",
          "function=>",
          "return",
          "export",
          "default"
        ]
      }
    },
    "params": 0,
    "sloc": {
      "logical": 4,
      "physical": 15
    }
  },
  "settings": {
    "commonjs": false,
    "forin": false,
    "logicalor": true,
    "switchcase": true,
    "trycatch": false,
    "newmi": false
  },
  "classes": [],
  "dependencies": [
    {
      "line": 1,
      "path": "react",
      "type": "esm"
    }
  ],
  "errors": [],
  "lineEnd": 15,
  "lineStart": 1,
  "maintainability": 162.615,
  "methods": [
    {
      "cyclomatic": 1,
      "cyclomaticDensity": 100,
      "halstead": {
        "bugs": 0.004,
        "difficulty": 1,
        "effort": 11.61,
        "length": 5,
        "time": 0.645,
        "vocabulary": 5,
        "volume": 11.61,
        "operands": {
          "distinct": 3,
          "total": 3,
          "identifiers": [
            "console",
            "log",
            "\"getInitialState...\""
          ]
        },
        "operators": {
          "distinct": 2,
          "total": 2,
          "identifiers": [
            "()",
            "."
          ]
        }
      },
      "params": 0,
      "sloc": {
        "logical": 1,
        "physical": 3
      },
      "errors": [],
      "lineEnd": 7,
      "lineStart": 5,
      "name": "<anonymous>"
    }
  ],
  "methodAverage": {
    "cyclomatic": 1,
    "cyclomaticDensity": 100,
    "halstead": {
      "bugs": 0.004,
      "difficulty": 1,
      "effort": 11.61,
      "length": 5,
      "time": 0.645,
      "vocabulary": 5,
      "volume": 11.61,
      "operands": {
        "distinct": 3,
        "total": 3
      },
      "operators": {
        "distinct": 2,
        "total": 2
      }
    },
    "params": 0,
    "sloc": {
      "logical": 1,
      "physical": 3
    }
  }
}
`

**Comment by yulongheli** [comment]
methods did not include getInitialState and render.

**Comment by typhonrt** [comment]
@yulongheli indeed functions within top level methods / functions will be supported in next major update as far as separate break out stats are concerned. The top level method metric does include the child function metrics presently. 

I've actually been working on a major ES6+ documentation tool called [TJSDoc](https://github.com/typhonjs-node-tjsdoc) that has taken the majority of my time since the beginning of the year. I plan to upgrade typhonjs-escomplex once that is launched and provide plugin integration for it regarding documentation generation that adds escomplex stats to the runtime doc DB along with really nice D3 graphs that go well beyond Plato right in the documentation itself for complexity info.

So, do please be patient. No hard ETA, but it's definitely planned / in progress.

**Comment by yulongheli** [comment]
thanks，looking forward to new features.

**Comment by typhonrt** [comment]
This issue was moved to typhonjs-node-escomplex/typhonjs-escomplex#6
